apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-demo
  namespace: cnpg-lab
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  enableSuperuserAccess: true

  storage:
    storageClass: premiumv2-disk-sc
    size: 10Gi

  walStorage:
    storageClass: premiumv2-disk-sc
    size: 5Gi

  superuserSecret:
    name: postgres-superuser

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-user
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: sample-data-sql
            key: sample.sql

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-lab-backups
        serverName: cnpg-demo
