apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-restore
  namespace: cnpg-lab
spec:
  instances: 3

  storage:
    storageClass: premiumv2-disk-sc
    size: 10Gi

  walStorage:
    storageClass: premiumv2-disk-sc
    size: 5Gi

  superuserSecret:
    name: postgres-superuser

  bootstrap:
    recovery:
      backup:
        name: cnpg-backup

  backup:
    barmanObjectStore:
      destinationPath: https://REPLACE_ME_ACCOUNT.blob.core.windows.net/REPLACE_ME_CONTAINER/acstor-cnpg-restore
      azureCredentials:
        storageAccount:
          name: azure-blob-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: azure-blob-creds
          key: AZURE_STORAGE_KEY
    retentionPolicy: "7d"
    target: "prefer-standby"
