apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-demo
  namespace: cnpg-lab
spec:
  instances: 3

  storage:
    storageClass: premiumv2-disk-sc
    size: 10Gi

  walStorage:
    storageClass: premiumv2-disk-sc
    size: 5Gi

  superuserSecret:
    name: postgres-superuser

  bootstrap:
    initdb:
      database: app
      owner: app
      secret:
        name: app-user
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: sample-data-sql
            key: sample.sql

  backup:
    barmanObjectStore:
      destinationPath: https://REPLACE_ME_ACCOUNT.blob.core.windows.net/REPLACE_ME_CONTAINER/acstor-cnpg
      azureCredentials:
        storageAccount:
          name: azure-blob-creds
          key: AZURE_STORAGE_ACCOUNT
        storageKey:
          name: azure-blob-creds
          key: AZURE_STORAGE_KEY
    retentionPolicy: "7d"
    target: "prefer-standby"
