apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cnpg-restore
  namespace: cnpg-lab
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:17

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser

  storage:
    storageClass: premiumv2-disk-sc
    size: 10Gi

  walStorage:
    storageClass: premiumv2-disk-sc
    size: 5Gi

  bootstrap:
    recovery:
      source: cnpg-demo
      database: app
      owner: app
      secret:
        name: app-user

  externalClusters:
    - name: cnpg-demo
      plugin:
        name: barman-cloud.cloudnative-pg.io
        parameters:
          barmanObjectName: cnpg-lab-backups
          serverName: cnpg-demo

  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: cnpg-lab-backups
        serverName: cnpg-restore
